sudo: false
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
before_script:
    - pip install -r build/build_requirements.txt
install:
    - pip install .
script:
    - coverage run --source="." trumpatron.py -k
    - build/build.sh
after_success:
    - coveralls