sudo: false
language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install pytest
    - pip install coveralls
script: build/build.sh
after_success: coveralls