sudo: false
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
before_script:
    - pip install -r build/build_requirements.txt
install:
    - pip install .
script:
    - coverage run --parallel-mode --source="." trumpatron.py -c conf/ro.cfg -t
    - coverage run --parallel-mode --source="." trumpatron.py -c conf/ro.cfg -t -n 3
    - coverage run --parallel-mode --source="." trumpatron.py -c conf/nonexistent.cfg -t || exit 0
    - coverage combine
    - ls -la
    - build/build.sh
after_success:
    - coveralls