dist: trusty
sudo: required
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
before_script:
    - pip install -r build/build_requirements.txt
    - sudo mkdir /var/log/trumpatron
    - sudo chown -R travis /var/log/trumpatron/
    - sudo chmod -R 774 /var/log/trumpatron/
install:
    - pip install .
script:
    - coverage run --parallel-mode --source="." trumpatron.py -c conf/ro.cfg -t
    - coverage run --parallel-mode --source="." trumpatron.py -c conf/ro.cfg -t -n 3
    - coverage combine
    - build/build.sh --no-tests
after_success:
    - coveralls